name: Golang-linter

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  golang_linter_action:
    runs-on: ubuntu-18.04
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
      GOPROXY: "https://proxy.golang.org"
    steps:
      - name: Setup Go Language
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14.1" # The Go version to download (if necessary) and use.

      - name: Checkout out our source
        uses: actions/checkout@v2

      - name: Check golang
        run: |
          ls -lah
          go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Testing
        run: go test ./... -v -race -coverprofile=coverage.out
